- crab/PSet.py
- crab/crab_cfg.py
- crab/crab_script.py
- crab/crab_script.sh
- python/postprocessing/examples/example_postproc.py
- python/postprocessing/framework/crabhelper.py
- python/postprocessing/framework/jobreport.py
- python/postprocessing/framework/output.py
- python/postprocessing/framework/postprocessor.py
- python/postprocessing/framework/preskimming.py
Run post processing on crab.
Support lumi-splitting and eventsAwareLumiSplitting
runsAndLumis json can now be passed as a dict rather than json file
Also introduce options to create FrameworkJobReport out of the python postprocessor (used by the crab config)
> Add crab scripts, options to save provenance in postprocessing and create FJR 

- python/postprocessing/modules/btv/btagSFProducer.py
- added workaround for the fact that BTagCalibrationReader::eval_auto_bounds() returns zero
in case jet pT > 30 or abs(eta) > 2.4
- fixed processing of btagSF for charm and bottom jets
> fixed bugs that caused btagSF to be evaluated to zero for some jets:

- README.md
- standalone/env_standalone.sh
Using `$0` as was done in the existing standalone setup script causes issues when this script is sourced within another.  Using BASH_SOURCE instead fixes this issue [1].  Also fixed a typo in the README for setting up in stand-alone mode.
[1] I think we're targeting Bash with that script give the parameter expansion `${0:0:1}` and bash 3 or more is pretty ubiquitous these days
> Fix readme and use BASH_SOURCE instead of $0

- python/postprocessing/framework/postprocessor.py
The "noOut" option was (trivially) broken. Now there is capability of NOT writing the output tree, which is basically the first step in converting this to a full analysis framework.
> Fix no out

- crab/crab_script.py
The "mht" module doesn't exist anymore, replace with "exampleModule".
> Replacing obsolete "mht" module

- python/postprocessing/modules/jme/jetmetUncertainties.py
Small change in implementation so that all-python JEC/JER implementation works with preliminary post-processor implementation.
> fix to get all-python JEC/JER implementation running

- python/postprocessing/modules/jme/jetmetUncertainties.py
When trying to run jetmetUncertainties module https://github.com/cms-nanoAOD/nanoAOD-tools/blob/271cf2c755c02292e7c64cafc720eb313ed9ce3a/python/postprocessing/modules/jme/jetmetUncertainties.py#L272 the JetCorrectorParameters instance is constructed from the file name $CMSSW_BASE/src/PhysicsTools/NanoAODTools/data/jme/Summer16_23Sep2016V4_MC_Uncertainty_AK4PFchs.txt and 'Total' as the uncertainty source/label https://github.com/cms-nanoAOD/nanoAOD-tools/blob/271cf2c755c02292e7c64cafc720eb313ed9ce3a/python/postprocessing/modules/jme/jetmetUncertainties.py#L57. This fails because the input file does not contain the label name between the brackets.
The solution is to set the label string to an empty one if only single JES uncertainty source (`'Total'`) is requested.
> Fix reading JES uncertainties file

- interface/WeightCalculatorFromHistogram.h
- python/postprocessing/modules/common/puWeightProducer.py
- src/WeightCalculatorFromHistogram.cc
- src/classes.h
- src/classes_def.xml
Moved PU weight producer to separate module, as ACLIC causes problems when running multiple jobs from the same working directory by overwriting/cleaning the temporary object files. Maybe there is a way to set the ACLIC compilation directory, but this seems cleaner.
> Move PU weight producer to module

- python/postprocessing/modules/btv/btagSFProducer.py
Dear all,
This PR improves the performance of the btag scale factor producer, `python/postprocessing/modules/btv/btagSFProducer.py`, by 40% (wall time).
A colleague of mine, @shane-breeze, observed that computing the btag scale factor does take a lot of time:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
43354   31.869    0.001  140.315    0.003 btagSFProducer.py:249(analyze)
7991874   63.137    0.000   76.069    0.000 btagSFProducer.py:196(getSF)
```
For our test sample this resulted in a total of
```
126005017 function calls (122184427 primitive calls) in 191.403 seconds
```
Looking at the code, we've found some improvement possibilities, the easiest ones are contained in this PR.
With the changes in place, the new profiling information is
```
53533045 …
```
> improving speed of btag scale factor retrieval

- python/postprocessing/modules/common/countHistogramsModule.py
Hi,
This module is intended to address these issues:
https://github.com/cms-nanoAOD/nanoAOD-tools/issues/28
https://github.com/cms-nanoAOD/nanoAOD-tools/issues/61
I have checked that haddnano.py properly sums the histograms
Andrew
> add a module which produces event count histograms

- python/postprocessing/modules/btv/btagSFProducer.py
In V2 of the btag scale factors, the shape corrections (iterativefit) are present:
~~~
$ grep iterativefit data/btagSF/CSVv2_94XSF_V2_B_F.csv | wc -l
1668
~~~
so we can now compute them:
~~~
root [1] Friends->Scan("Jet_btagSF_shape:Jet_btagSF_shape_down_lf")
***********************************************
*    Row   * Instance * Jet_btagS * Jet_btagS *
***********************************************
*        0 *        0 * 1.0267343 * 1.0023125 *
*        0 *        1 * 0.9355568 * 0.9355568 *
*        0 *        2 * 1.5425299 * 1.5425299 *
*        0 *        3 * 0.9145733 * 0.8872598 *
*        0 *        4 * 1.0338901 * 0.9968101 *
*        0 *        5 * 1.0507129 * 1.0053309 *
*        0 *        6 * 0.9969844 * 0.9969844 *
*        0 *        7 * 0.9994378 * 0.9994378 *
*        0 * …
> enable shape corr for btag SF v2

- python/postprocessing/modules/btv/btagSFProducer.py
From [BTagShapeCalibration Twiki](https://twiki.cern.ch/twiki/bin/view/CMS/BTagShapeCalibration?rev=19#Brief_description_of_the_Tag_and):
> Apply the scale factor based on the jet flavor (pfJet->hadronFlavour())
In CMSSW nanoAOD fork, the inclusive event-level b-tagging weight is also computed based on hadronFlavour of jets ([link](https://github.com/cms-nanoAOD/cmssw/blob/a348544b0d03cbf135953ce23c27ea2b4723327c/PhysicsTools/NanoAOD/plugins/BTagSFProducer.cc#L197)).
> Use hadronFlavour instead of partonFlavour in btagSFProducer

- README.md
- interface/mhtjuProducerCppWorker.h
- python/postprocessing/examples/exampleModule.py
- scripts/keep_and_drop.txt
- scripts/keep_and_drop_input.txt
- scripts/keep_and_drop_output.txt
- scripts/nano_postproc.py
- src/mhtjuProducerCppWorker.cc
Improved instructions in readme file. Now all should work.
Removed dependency LorentzVector from CMSSW, so the mht producer should works standalone as well.
> Working readme examples

- python/postprocessing/modules/jme/jetmetUncertainties.py
This PR adds branches for the nominal correction factors (JEC and JER) applied within the jetmetUncertainties post processing module. This is necessary to recalculate the uncorrected pt after post processing. W/o this change it is not possible to do this if a new JEC is applied in module.
**New Branches:**
- Jet_corr_JEC *(is equal to 1/(1-rawFactor) if no new JEC is applied in module)*
- Jet_corr_JER
Defined so that: Jet_pt_nom = Jet_pt_raw * Jet_corr_JEC * Jet_corr_JER
> Nominal correction factors in jetmetUncertainties

- python/postprocessing/framework/postprocessor.py
This PR suggests to modify postprocessor to support friend tree in the input.
Use case: Users have centrally produced NanoAOD root file and Friend tree. 
They want to read branches across two (or >2) files.
Usage:
```
nano_postproc nano_postproc.py --friend -I Some.User.Module userModule nanoAOD.root,friend.root,friend2.root
```
> Secondary file input to postprocessor

- python/postprocessing/modules/jme/jetRecalib.py
- python/postprocessing/modules/jme/jetSmearer.py
- python/postprocessing/modules/jme/jetmetUncertainties.py
Module updates separated out from PR #126.
Accommodates the fact that JECs will be stored in tgz files now.
> JME module update for 2017 and (preliminary) 2018 JECs

- python/postprocessing/framework/preskimming.py
Add a feature to support skimming with a cutstring when some branches may be missing. The main usecase is to skim with a cutstring in the form `HLT_Path1 || HLT_Path2  || HLT_Path3` when a path may be missing in some runs and thus in some input files.
It seems like `Alt$(name,0)` does not work for this case, as a missing branch still raises an error.
So, this PR adds a syntax `AltBranch$(name,value)` , or `AltBranch$(name,name2)`,  where the preprocessor checks once if the branch exists and replaces the expression with the proper value.
@peruzzim
> Support for missing branches in cutstring when skimming

- python/postprocessing/framework/eventloop.py
Defining the `Module` class with
```
class Module(object):
...
```
makes it a new-style class, allowing `super()` to be used in subclasses, e.g.
```
class MyModule(Module):
def __init__(self,*args):
super(MyModule,self).__init__()
...
class MySubModule(MyModule):
def __init__(self,*args):
super(MySubModule,self).__init__(*args)
...
```
Without this, there will be type error because of the use of `super`:
```TypeError: must be type, not classobj```
See e.g. https://stackoverflow.com/a/1713052
> Make Module class a new-style class

- python/postprocessing/framework/eventloop.py
Trivial fix, but important if one is producing friend trees splitting a single input file in multiple tasks processing different ranges of entries.
@peruzzim 
@fgolf given it's a trivial bugfix I'll merge it directly
> Fix maxEvents range when not skimming (was missing last event)

- python/postprocessing/framework/datamodel.py
Added simple class method to quickly compute the DeltaR between two objects without the need to create the `TLorentzVector` objects, e.g.
```
if event.nMuon>=2:
muons = Collection(event,'Muon')
dR0 = muons[0].p4().DeltaR(muons[1].p4()) # create two TLorentzVectors on the fly
dR1 = muons[0].DeltaR(muons[1])           # using this new method
dR2 = muons[0].DeltaR(muons[1].p4())      # using this new method, passing TLorentzVector
``` 
Comparing these three methods for a large number of events, I found no difference between them beyond rounding errors sometimes, with a relative difference on the order of 10^-16.
> Add DeltaR to Object class

- python/postprocessing/modules/jme/jetRecalib.py
- python/postprocessing/modules/jme/jetSmearer.py
- python/postprocessing/modules/jme/jetmetUncertainties.py
Found that our local cluster ran out of memory because the files that were unpacked from these tarballs were never removed.
> Remove files that were unpacked from JES & JER tarballs to a temp dir

- crab/crab_script.py
Most users use this script as-is and end un with very long output where the full directory three is printed in each job. Long outputs put strain on submission infrastructure and CRAB servers. Users should only do this when really needed, and for a few jobs. Listing same directory in each job in a task is totally useless.
> remove directory tree listing

- src/WeightCalculatorFromHistogram.cc
Currently, the cropped vector will grow larger and larger in each iteration, while it should always have a fixed length or be empty.
> Fix bug in large pileup weight handling

- python/postprocessing/modules/jme/JetReCalibrator.py
This addresses issue #198 by setting the jet phi in JetReCalibrator.py.
> Updated JetReCalibrator.py to allow for phi-dependent JECs

- scripts/haddnano.py
Backfilling also the Run tree in both boolean and non-boolean branches.
This is needed to support multi-point signal scans (cms-nanoAOD/cmssw#398).
To be tested thoroughly
> Backfill Run tree in haddnano to support multi-point signal scans

- python/postprocessing/modules/common/puWeightProducer.py
The wrong data pileup histogram was used in the puWeightProducer for 2017.
> Use the correct data PU histogram for 2017

- python/postprocessing/framework/output.py
- python/postprocessing/modules/common/collectionMerger.py
This PR fixes three issues I have encountered when working with collection merging and output filtering:
1. the output branch selection definition is applied to `collectionMerger` output. 
2. output branch selection is applied to newly created branches. This is useful for filtering a new collection based on branches that do not exist at the beginning of the run. For example, one might want to filter jet candidates based on their JES-corrected properties.
3. `collectionMerger` correctly copies newly made branches to the new collection. Previously, it would ignore these.
An example implementation of a scenario where these three issues come into play is given [in this gist](https://gist.github.com/AndreasAlbert/d06a512534b88a812e8ea8718b8bb7bb).
> Improvements to output filtering

- python/postprocessing/framework/output.py
After updating to the latest version (and picking up #203 and #218 ) I get the following error:
```bash
% nano_postproc.py -I PhysicsTools.NanoAODTools.postprocessing.modules.jme.jetmetUncertainties jetmetUncertainties2016All -I PhysicsTools.NanoAODTools.postprocessing
.modules.btv.btagSFProducer btagSF2016 --postfix=testJME . ~/bamboodev/bamboo/tests/data/DY_M50_2016.root > log
Traceback (most recent call last):                               
File "/home/users/p/d/pdavid/bamboodev/NanoAODTools/CMSSW_11_0_0_pre4/bin/slc7_amd64_gcc700/nano_postproc.py", line 73, in <module>                                                                            
p.run()                                                                                       
File …
```
> Fix #203 in case no outputbranchSelection is defined

- python/postprocessing/modules/jme/fatJetUncertainties.py
- python/postprocessing/modules/jme/jetmetHelperRun2.py
Updated 2018 JMS and JMR scale factors for FatJets from https://twiki.cern.ch/twiki/bin/view/CMS/JetWtagging
> Added JMS and JMR sf for FatJet for 2018 in jetmetHelper

- python/postprocessing/modules/jme/jetmetUncertainties.py
As pointed out in #221 the central JER smeared value of MET is not getting the v2 correction applied, which is fixed with this PR.
> fix JER central value for METv2 recipe in 2017

- python/postprocessing/modules/btv/btagSFProducer.py
Currently, the `btagSFProducer` module will only add the SFs for a single working point (hardcoded to `M`). Furthermore, the naming of the branches (`Jet_btagSF`) prevents the user to add SFs for several taggers. Finally, the shape correction SFs include systematic variations that have to be correlated with the JEC variations. By default only the total uncertainty is taken into account, but in case one uses SFs which include the split (or reduced) JEC uncertainty sources, one would like to have all the corresponding SF variations stored as well. 
With this PR, the user can select all the working points he'd like (default: `['M', 'shape_corr']`), and the branches are now named as e.g. `Jet_btagSF_<tagger>_<WP>` so that several modules can be added to get the SFs for different taggers. …
> B-tagging scale factors: multiple working points or taggers; specify list of JEC uncertainties

- python/postprocessing/framework/eventloop.py
I think it is more useful to count wall time of event processing with time.time() rather than time.clock(). This would be more useful for timing comparisons.
Example: if a file served via xrootd it may take much longer to run, but the progress with time.clock() reports the CPU time as though it runs from a local machine.
> Replace time.clock() with time.time()

- python/postprocessing/modules/common/PrefireCorr.py
This PR does not change the default behavior of the prefiring module.
It adds the ability to customize the branch naming for the output branches, so that it becomes possible to save the weights from both prefiring options (either using the nominal or EM jet pt) in the same run into different branches.
> Prefiring weights: Allow customization of output branch names

- python/postprocessing/modules/jme/jetmetUncertainties.py
There is a discrepancy of the propagation of JES variations to type-1 MET between CMSSW and NanoAOD-tools. Discussed here:
https://indico.cern.ch/event/921037/contributions/3869620/attachments/2042217/3420993/nanoaod_jes_talk_v2.pdf
The fix was tested for 2017 (with METv2 recipe) and 2018. Consistent results up to the numerical precision of nanoAOD and the following bin migrations are now achieved.
> JES uncertainty fix

- python/postprocessing/modules/jme/jetmetUncertainties.py
Re-applying Type-1 Correction for PuppiMET does not work currently since the wrong input MET collection is used (PF MET).
This PR switches the collection used to the appropriate one for PuppiMET
This is important going forward when the Puppi objects become default in the future and also for using with custom JME NanoAODs where the re-application of Type-1 corrections for PuppiMET will become useful.
> Fixing MET collection used for applying Type1 corrections for PupiMET

- python/postprocessing/framework/datamodel.py
- python/postprocessing/framework/postprocessor.py
- src/WeightCalculatorFromHistogram.cc
Here is just few small proposals for updates:
* make it possible in p4() method to provide a new pT, that is, use p4(corr_pt). This is useful to replace the muon momentum with corrected_pt variables from rochester correction functions.
* changed time.clock to time.time, to be consistent with #226 
* imporoved the way output branches are masked (keep and drop file). If input mask is provided, but the output mask is not, the input mask is used for the output as well. The branches masked at the input are empty in the output anyway. If the output mask is provided - it is used instead (it should be more restrictive than input, but this is not checked).
> Minor updates to the code: p4() with correced pT; clock() to time() change

- python/postprocessing/modules/jme/jetSmearer.py
- python/postprocessing/modules/jme/jetmetHelperRun2.py
- python/postprocessing/modules/jme/jetmetUncertainties.py
This PR contains new code that has:
- Separate calculations of JME uncertainties for T1 and T1Smear MET, which are stored in different branches
- An option flag in jetmetHelper to specify which MET uncertainties (T1 or T1Smear) are to be saved
> Updates on T1Smear MET calculation: Central value + JME uncertainties

- python/postprocessing/framework/postprocessor.py
This PR fixes a missing `not` in `python/postprocessing/framework/postprocessor.py`. I made a [comment](https://github.com/cms-nanoAOD/nanoAOD-tools/pull/255/files#r521145897) here in PR #255.
> Fix missing 'not'

- python/postprocessing/modules/jme/jetmetUncertainties.py
Since the loop over JES uncertainty sources was put inside the one over JER bins in https://github.com/cms-nanoAOD/nanoAOD-tools/pull/244, the JES variations are applied six times instead of once if JER uncertainty splitting is enabled.
I just removed the indentation, but I guess this also allows for some of the line splitting to be reverted - let me know if there's some script/guideline for this.
> Fix JES uncertainties on T1(smear) MET with split JER (indentation)

- python/postprocessing/framework/branchselection.py
- python/postprocessing/framework/treeReaderArrayTools.py
This PR introduces two technical updates:
- https://github.com/cms-nanoAOD/nanoAOD-tools/commit/0ac785c849d7d4cac327265a423e41414603874c changes the code to raise an error when reading a TTree branch on which `SetBranchStatus(name, 0)` has been called (i.e., when they are dropped in the `keep_and_drop` file). Otherwise the branch reading fails silently, leading to hard-to-detect errors.
- https://github.com/cms-nanoAOD/nanoAOD-tools/commit/bd96eb46171a9ed0824750f65c7fe949e69ac858 fixes a crash in python 3.7+ due to changes in python's `re` package.
> Two technical updates

- python/postprocessing/helpers/TauIDSFTool.py
- python/postprocessing/helpers/TauTriggerSFTool.py
- python/postprocessing/modules/common/tauCorrProducer.py
- python/postprocessing/tools.py
This makes the tau tools compatible with python3 and non-CMSSW standalone use as per request https://github.com/cms-nanoAOD/nanoAOD-tools/pull/258#issuecomment-773411712. Tested with both python 2.7 and 3.6 (via `source /cvmfs/sft.cern.ch/lcg/views/LCG_96python3/x86_64-centos7-gcc8-opt/setup.sh`) User can set the path to the data files, which otherwise assumes a `CMSSW_BASE` environmental variable.
> Make tau tools python3 and standalone compatible

- python/postprocessing/modules/jme/jetmetUncertainties.py
Fixes #259 
- rename `MET_(pt,phi)_unclustEn(Up,Down)` -> `MET_T1_(pt,phi)_unclustEn(Up,Down)`
- add `MET_T1Smear_(pt,phi)_unclustEn(Up,Down)` with the same variations calculated with respect to the smeared Type-1 MET.
See also https://github.com/cms-nanoAOD/nanoAOD-tools/pull/256#issuecomment-732112530
Validation: [printout](https://github.com/cms-nanoAOD/nanoAOD-tools/files/5582879/scan_unclustEnSmeared.log) of the relevant variations for master and with the changes for a few events. `MET_T1_*_unclustEn*` is the same as the old branch (rename), the new `MET_T1Smear_(pt,phi)_unclustEn(Up,Down)` variations are in line with expectations.
> Unclustered energy variations for T1Smear

- python/postprocessing/framework/output.py
The tree is already filtered just before writing, so `firstEntry>0` in https://github.com/cms-nanoAOD/nanoAOD-tools/blob/25a793ec55b30fe7107af263c4523f20ff1a5fbd/python/postprocessing/framework/output.py#L175-L176 causes a loss of events. See https://github.com/cms-nanoAOD/nanoAOD-tools/issues/269.
> Fix firstEntry bug

- python/postprocessing/framework/postprocessor.py
- python/postprocessing/framework/treeReaderArrayTools.py
As mentioned in [this](https://github.com/cms-nanoAOD/nanoAOD-tools/issues/277) issue, a conversion error is thrown when running the postprocessor with newer versions of ROOT. In particular, it is complaining about the TEntryList being supplied to the constructor. I believe this is because `entrylist` is NoneType by default, rather than a null pointer. By replacing this default value with `ROOT.MakeNullPointer(ROOT.TEntryList)`, the `TTreeReader` constructor instead receives a nullpointer as it expects. I tested this simple fix using CMSSW v12.1.0 (pre, with ROOT v6.24) and CMSSW v10.6.25. I used a custom module and skimmed some custom MC signal samples for the test.
> Fixed null pointer conversion error for newer versions of ROOT

- python/postprocessing/framework/postprocessor.py
This is a solution to Issue https://github.com/cms-nanoAOD/nanoAOD-tools/issues/274, which reported that in the special case where the user passes no modules (such that `fullClone==True`), but passes a JSON file via the `jsonInput` option, and/or a cut via `cut`, there seems to a loss of events, because the entry index is not properly shifted when an event list (vector `elist`) is created. @gouskos
I checked different settings. This is before fixing the bug:
```
firstEntry maxEntry           cut     json    ntot   full event range   entries 0-99       entries 100-199  
0      200          None    False     200   67064147-68648544  67082251-68648544  67064147-68609297
0      200          None    False     200   67064147-68648544  67082251-68648544  67064147-68609297
0      200 …
```
> Fix firstEntry bug for fullClone

- python/postprocessing/modules/jme/fatJetUncertainties.py
When using `fatJetUncertaintiesProducer` with UL era (e.g. UL2018) the code crashes  in [this line](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/e963c7080606607777b083f59d752fe67b766265/python/postprocessing/modules/jme/fatJetUncertainties.py#L654), since `era` string doesn't cover UL cases in the [previous if statement](https://github.com/cms-nanoAOD/nanoAOD-tools/blob/e963c7080606607777b083f59d752fe67b766265/python/postprocessing/modules/jme/fatJetUncertainties.py#L630). With this simple fix the code works. Please note, that the corrections in [JetWtagging twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetWtagging) doesn't have separate factors for UL.
This issue was reported here: https://github.com/cms-nanoAOD/nanoAOD-tools/issues/285
@lathomas, @kirschen, @gouskos, …
> Add UL case for JMS&JMR SD corr in fatJetUncertainties

- python/postprocessing/framework/postprocessor.py
TL;DR: Quick fix to avoid crashes when no events in a job gets pre-selected when running code via e.g. crab.
Long version: in a previous PR I solved an issue with NanoAODTools crashing if no events got pre-selected in one of the input files (https://github.com/cms-nanoAOD/nanoAOD-tools/pull/303). However, in that solution we stopped processing the event straight after the pre-selection, thus not adding anything to the job report or creating any output files. This was fine for running interactively, but caused issues if you submitted a job to e.g. crab if no events in the job got pre-selected. Then it tried to run the haddnano.py script merging the non-existent output files and crashing, and the crab jobs were also looking for the outputs and crashed when they were not found. In this PR I …
> Fix crash when no entries are pre-selected in a crab job

- python/postprocessing/framework/postprocessor.py
- scripts/haddnano.py
This PR adds a simple if-statement to protect to the case were zero events were preselected.
I ran into this error for several data files for which no events were in the good event list of the golden JSON, leading to failing jobs (`self.noOut` set to `True`). Otherwise I have to manually filter the input file list for the jobs.
> Protect against files with zero pre-selected events

- scripts/haddnano.py
A THnSparse object is needed to save the models in pMSSM. For other analysis using nanoAOD tools within SUSY that are involved in the pMSSM paper this will be needed.
> merge THnSparse object in haddnano

- python/postprocessing/framework/postprocessor.py
This bug appears when using the prefetch option in python3:
```
$ python2 -c "import os; print(type(os.urandom(8))); print(ord(os.urandom(8)[1]))"
<type 'str'>
106
$ python3 -c "import os; print(type(os.urandom(8))); print(ord(os.urandom(8)[1]))"
<class 'bytes'>
Traceback (most recent call last):
File "<string>", line 1, in <module>
TypeError: ord() expected string of length 1, but int found
```
For python3, `ord` should be removed for this to work.
The best solution for keeping compatibility between both python2 and python3 I could immediately find is using `bytearray`
```
$ python2 -c 'import os; a=os.urandom(8); print(", ".join([hex(ord(i))[2:] for i in a])); print(", ".join([hex(i)[2:] for i in bytearray(a)]))'
38, 6e, b3, d2, fb, 70, 4d, e6
38, 6e, b3, d2, fb, 70, 4d, e6
$ python3 -c …
```
> Fix ord bug in prefetch for python2-3 compatibility

- README.md
The README file now mentions that NanoAODTools is maintained within CMSSW since 13X.
> Update README.md to mention the new CMSSW package
