cms-nanoAOD/nanoAOD-tools

- python/postprocessing/examples/lepSFProducer.py
- python/postprocessing/helpers/LeptonEfficiencyCorrector.cc
- python/postprocessing/helpers/WeightCalculatorFromHistogram.cc
> Fix for paths of modules

- python/postprocessing/helpers/WeightCalculatorFromHistogram.cc
Fix the direction of the reweighting (should be target/ref, not the opposite).
Also add some regularisation.
> fix  PU reweighting

- python/postprocessing/modules/jme/jecUncertainties.py
Path changed due to commit https://github.com/cms-nanoAOD/nanoAOD-tools/commit/fabdfdbff93c5ce1b70c238a2fc96ef091db5c65
> Fix the path to JEC files in jecUncertainties module

- python/postprocessing/framework/output.py
In case one adds a branch that was already there, the existing branch is first scratched from the output tree and the new one is then added.
> Recompute existing branches

- data/btagSF/CSVv2_94XSF_V2_B_F.csv
- data/btagSF/DeepCSV_94XSF_V2_B_F.csv
Btag scale factor files where not in correct CSV format, fixed that by redownloading from https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
> fix btag sf file

- python/postprocessing/modules/common/muonScaleResProducer.py
Without this protection in place, some rare events will crash the jobs.
>  add protection to muonScaleResProducer.py

- python/postprocessing/framework/output.py
This should enable overwriting branches with the same name, as per issue #81
> Recompute existing branches v2

- python/postprocessing/framework/postprocessor.py
Fix for issue [Variable 'nall' referenced before assignment in postprocessor.py](Variable 'nall' referenced before assignment in postprocessor.py).
> nall variable fix

- scripts/nano_postproc.py
> Add keep and drop in the outbranches too

- crab/crab_cfg.py
- crab/crab_script.py
After pull #102 crab_script.py needed to be changed (rename the exampleModule to exampleModuleConstr)
> Fix crab scripts

- python/postprocessing/helpers/LeptonEfficiencyCorrector.cc
Update import path of WeightCalculatorFromHistogram.cc in LeptonEfficiencyCorrector.cc to align with updates in commit https://github.com/cms-nanoAOD/nanoAOD-tools/commit/39701813f3bb1d99e53b49ed5a84ea275f01a7c4
> Update import path of WeightCalculatorFromHistogram.cc in LeptonEfficiencyCorrector.cc

- python/postprocessing/modules/common/countHistogramsModule.py
The weighted histogram should be filled with a negative weight in the same bin.
> fix bug in filling weighted count histogram

- python/postprocessing/modules/jme/mht.py
Correcting missing branch miniPFIso_all to miniPFRelIso_all
> Correcting missing branch miniPFIso_all to miniPFRelIso_all

- python/postprocessing/framework/output.py
- python/postprocessing/framework/postprocessor.py
- python/postprocessing/framework/preskimming.py
- scripts/nano_postproc.py
* fix the path to `haddnano.py` (take from the system path if it's not in the current directory)
* support for prefetching input files with xrdcp (can be faster than running with AAA depending on latencies & networking)
* support for processing only part of the entries in a file (useful for local processing)
> Some postprocessor developments

- python/postprocessing/framework/postprocessor.py
Allow for branch selection of input tree if `noOut==True` to speed up computation.
> Allow for branch selection if noOut

- python/postprocessing/framework/eventloop.py
- python/postprocessing/framework/postprocessor.py
* Better handling of cases with eventRange and maxEntries
* Better reporting of efficiencies and rates
> Small postprocessor improvements in splitting and logging

- python/postprocessing/modules/jme/JetReCalibrator.py
This fixes the pt assignment reported in #145.  It also fixes a few other bugs.  These weren't discovered previously as the getCorrection() method isn't used in this repository so far.
> Fix Jetrecalibrator bugs reported in issue #145

- python/postprocessing/modules/jme/jetmetUncertainties.py
> Fixup genjet matching for JER

- python/postprocessing/modules/jme/jetmetHelperRun2.py
Hi @gouskos 
Correcting a typo at line 52, missing "," at the end of the line I think
> Fix a typo at line 52

- python/postprocessing/framework/crabhelper.py
- python/postprocessing/framework/eventloop.py
- python/postprocessing/framework/postprocessor.py
- python/postprocessing/modules/common/PrefireCorr.py
- python/postprocessing/modules/jme/jetSmearer.py
- scripts/haddnano.py
- scripts/nano_postproc.py
As @andreypz pointed out in the comment of PR cms-nanoAOD#251, then there was a mistake in one of the print statements that was introduced in that PR. Added the str() to the print statement and made some further pep8.
> Typo fix (#6)

- python/postprocessing/framework/datamodel.py
I added a check for negative indices when accessing an element in a Collection, so now it throws and error if a negative index is used.
> Added check for negative indices in Collection class

- python/postprocessing/examples/exampleGenDump.py
- python/postprocessing/framework/datamodel.py
- python/postprocessing/tools.py
This small class method would help simplify some code and make it more readable:
```
for part in Collection(event,'GenPart'):
isPrompt = part.statusflag('isPrompt')
isPromptHard = part.statusflag('isPrompt','fromHardProcess')
```
I left the `statusflags` dictionary global in `datamodel.py` so the user can still update the dictionary if needed in the future, or import it for some other purpose
```
import PhysicsTools.NanoAODTools.postprocessing.framework.datamodel as datamodel
datamodel.statusflags['fromHardProcess'] = 8
datamodel.statusflags['hard'] = 8 # shorthand
```
> Add statusflag help function to Object class
